# MPLAB IDE generated this makefile for use with GNU make.
# Project: USB Device - HID - Keyboard- C18 - PICDEM FSUSB.mcp
# Date: Wed Jul 13 22:39:23 2011

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

USB\ Device\ -\ HID\ -\ Keyboard-\ C18\ -\ PICDEM\ FSUSB.cof : Objects/USB\ Device\ -\ HID\ Keyboard\ -\ C18\ -\ PICDEM\ FSUSB/usb_descriptors.o Objects/USB\ Device\ -\ HID\ Keyboard\ -\ C18\ -\ PICDEM\ FSUSB/usb_device.o Objects/USB\ Device\ -\ HID\ Keyboard\ -\ C18\ -\ PICDEM\ FSUSB/usb_function_hid.o Objects/USB\ Device\ -\ HID\ Keyboard\ -\ C18\ -\ PICDEM\ FSUSB/Keyboard.o
	$(LD) /l"C:\mcc18\lib" "18f2550.lkr" "Objects\USB Device - HID Keyboard - C18 - PICDEM FSUSB\usb_descriptors.o" "Objects\USB Device - HID Keyboard - C18 - PICDEM FSUSB\usb_device.o" "Objects\USB Device - HID Keyboard - C18 - PICDEM FSUSB\usb_function_hid.o" "Objects\USB Device - HID Keyboard - C18 - PICDEM FSUSB\Keyboard.o" /u_CRUNTIME /z__MPLAB_BUILD=1 /m"USB Device - HID - Keyboard- C18 - PICDEM FSUSB.map" /w /o"USB Device - HID - Keyboard- C18 - PICDEM FSUSB.cof"

Objects/USB\ Device\ -\ HID\ Keyboard\ -\ C18\ -\ PICDEM\ FSUSB/usb_descriptors.o : usb_descriptors.c ../../../../../MCC18/h/stdio.h ../../../../../MCC18/h/stdlib.h ../../../../../MCC18/h/string.h ../../Microchip/Include/USB/usb_device.h usb_descriptors.c ../../Microchip/Include/GenericTypeDefs.h ../../Microchip/Include/Compiler.h ../../../../../MCC18/h/p18cxxx.h ../../../../../MCC18/h/p18f2550.h ../../../../../MCC18/h/stdarg.h ../../../../../MCC18/h/stddef.h usb_config.h ../../Microchip/Include/USB/usb_ch9.h ../../Microchip/Include/USB/usb_hal.h ../../Microchip/Include/USB/usb_hal_pic18.h ../../Microchip/Include/USB/usb_function_hid.h
	$(CC) -p=18F2550 /i"C:\MCC18\h" -I"..\..\Include" -I"..\..\..\Include" -I"..\..\Microchip\Include" -I"..\..\USB Device - HID - Keyboard\Firmware" -I"..\..\..\USB Device - HID - Keyboard\Firmware" "usb_descriptors.c" -fo=".\Objects\USB Device - HID Keyboard - C18 - PICDEM FSUSB\usb_descriptors.o" -pa=4

Objects/USB\ Device\ -\ HID\ Keyboard\ -\ C18\ -\ PICDEM\ FSUSB/usb_device.o : ../../Microchip/USB/usb_device.c ../../../../../MCC18/h/stdio.h ../../../../../MCC18/h/stdlib.h ../../../../../MCC18/h/string.h ../../Microchip/Include/usb/usb_common.h ../../Microchip/Include/usb/usb_device.h ../../Microchip/USB/usb_device.c ../../Microchip/Include/GenericTypeDefs.h ../../Microchip/Include/Compiler.h ../../../../../MCC18/h/p18cxxx.h ../../../../../MCC18/h/p18f2550.h ../../../../../MCC18/h/stdarg.h ../../../../../MCC18/h/stddef.h ../../Microchip/Include/USB/usb_ch9.h ../../Microchip/Include/USB/USB.h usb_config.h ../../../../../MCC18/h/limits.h ../../Microchip/Include/usb/usb_ch9.h ../../Microchip/Include/usb/usb_hal.h ../../Microchip/Include/USB/usb_hal_pic18.h ../../Microchip/Include/USB/usb_hal.h ../../Microchip/Include/USB/usb_device.h HardwareProfile.h
	$(CC) -p=18F2550 /i"C:\MCC18\h" -I"..\..\Include" -I"..\..\..\Include" -I"..\..\Microchip\Include" -I"..\..\USB Device - HID - Keyboard\Firmware" -I"..\..\..\USB Device - HID - Keyboard\Firmware" "..\..\Microchip\USB\usb_device.c" -fo=".\Objects\USB Device - HID Keyboard - C18 - PICDEM FSUSB\usb_device.o" -pa=4

Objects/USB\ Device\ -\ HID\ Keyboard\ -\ C18\ -\ PICDEM\ FSUSB/usb_function_hid.o : ../../Microchip/USB/HID\ Device\ Driver/usb_function_hid.c ../../../../../MCC18/h/stdio.h ../../../../../MCC18/h/stdlib.h ../../../../../MCC18/h/string.h ../../Microchip/Include/USB/usb_device.h ../../Microchip/USB/HID\ Device\ Driver/usb_function_hid.c ../../Microchip/Include/GenericTypeDefs.h ../../Microchip/Include/Compiler.h ../../../../../MCC18/h/p18cxxx.h ../../../../../MCC18/h/p18f2550.h ../../../../../MCC18/h/stdarg.h ../../../../../MCC18/h/stddef.h usb_config.h ../../Microchip/Include/USB/usb_ch9.h ../../Microchip/Include/USB/usb_hal.h ../../Microchip/Include/USB/usb_hal_pic18.h ../../Microchip/Include/USB/usb_function_hid.h
	$(CC) -p=18F2550 /i"C:\MCC18\h" -I"..\..\Include" -I"..\..\..\Include" -I"..\..\Microchip\Include" -I"..\..\USB Device - HID - Keyboard\Firmware" -I"..\..\..\USB Device - HID - Keyboard\Firmware" "..\..\Microchip\USB\HID Device Driver\usb_function_hid.c" -fo=".\Objects\USB Device - HID Keyboard - C18 - PICDEM FSUSB\usb_function_hid.o" -pa=4

Objects/USB\ Device\ -\ HID\ Keyboard\ -\ C18\ -\ PICDEM\ FSUSB/Keyboard.o : Keyboard.c ../../../../../MCC18/h/stdio.h ../../../../../MCC18/h/stdlib.h ../../../../../MCC18/h/string.h ../../Microchip/Include/USB/usb_device.h ../../Microchip/Include/usb/usb_common.h ../../../../../MCC18/h/usart.h Keyboard.c ../../Microchip/Include/GenericTypeDefs.h ../../Microchip/Include/Compiler.h ../../../../../MCC18/h/p18cxxx.h ../../../../../MCC18/h/p18f2550.h ../../../../../MCC18/h/stdarg.h ../../../../../MCC18/h/stddef.h usb_config.h ../../Microchip/Include/USB/usb_ch9.h ../../Microchip/Include/USB/usb_hal.h ../../Microchip/Include/USB/usb_hal_pic18.h ../../Microchip/Include/USB/usb.h ../../../../../MCC18/h/limits.h ../../Microchip/Include/usb/usb_ch9.h ../../Microchip/Include/usb/usb_hal.h ../../Microchip/Include/usb/usb_device.h ../../../../../MCC18/h/pconfig.h HardwareProfile.h ../../Microchip/Include/USB/usb_function_hid.h
	$(CC) -p=18F2550 /i"C:\MCC18\h" -I"..\..\Include" -I"..\..\..\Include" -I"..\..\Microchip\Include" -I"..\..\USB Device - HID - Keyboard\Firmware" -I"..\..\..\USB Device - HID - Keyboard\Firmware" "Keyboard.c" -fo=".\Objects\USB Device - HID Keyboard - C18 - PICDEM FSUSB\Keyboard.o" -pa=4

clean : 
	$(RM) "Objects\USB Device - HID Keyboard - C18 - PICDEM FSUSB\usb_descriptors.o" "Objects\USB Device - HID Keyboard - C18 - PICDEM FSUSB\usb_device.o" "Objects\USB Device - HID Keyboard - C18 - PICDEM FSUSB\usb_function_hid.o" "Objects\USB Device - HID Keyboard - C18 - PICDEM FSUSB\Keyboard.o" "USB Device - HID - Keyboard- C18 - PICDEM FSUSB.cof" "USB Device - HID - Keyboard- C18 - PICDEM FSUSB.hex" "USB Device - HID - Keyboard- C18 - PICDEM FSUSB.map"

